apiVersion: apps/v1
kind: Deployment
metadata:
  name: cats-dogs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cats-dogs
  template:
    metadata:
      labels:
        app: cats-dogs
    spec:
      containers:
        - name: cats-dogs-container
          image: koelmlops/cats-dogs-mlops:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000